# Generated by Django 4.1.13 on 2024-05-29 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0002_accession_subject_comment_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='accession',
            new_name='specimen_no',
        ),
        migrations.RemoveField(
            model_name='accession',
            name='nature_specimen',
        ),
        migrations.AlterField(
            model_name='accession',
            name='specimen_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='abbreviation',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='response',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('C', 'Closed')], help_text='Please select your response', max_length=50),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(max_length=255)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('parent_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.storage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('field_number', models.CharField(max_length=100)),
                ('discoverer', models.CharField(max_length=255)),
                ('collector', models.CharField(max_length=255)),
                ('collection_date', models.DateField()),
                ('verbatim_locality', models.CharField(max_length=255)),
                ('verbatim_taxon', models.CharField(max_length=255)),
                ('verbatim_element', models.CharField(max_length=255)),
                ('verbatim_horizon', models.CharField(max_length=255)),
                ('aerial_photo', models.CharField(max_length=255)),
                ('verbatim_latitude', models.CharField(max_length=255)),
                ('verbatim_longitude', models.CharField(max_length=255)),
                ('verbatim_SRS', models.CharField(max_length=255)),
                ('verbatim_coordinate_system', models.CharField(max_length=255)),
                ('verbatim_elevation', models.CharField(max_length=255)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.accession')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
