# Generated by Django 4.1.13 on 2024-06-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_rename_accession_comment_specimen_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accession',
            name='type_status',
            field=models.CharField(choices=[('Type', 'Type'), ('Holotype', 'Holotype'), ('Isotype', 'Isotype'), ('Lectotype', 'Lectotype'), ('Syntype', 'Syntype'), ('Isosyntype', 'Isosyntype'), ('Paratype', 'Paratype'), ('Neotype', 'Neotype'), ('Topotype', 'Topotype')], default='Type', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldslip',
            name='verbatim_method',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='specimen_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms.accession'),
        ),
    ]
