# Generated by Django 4.1.13 on 2024-06-14 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0006_alter_accession_comment_alter_comment_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='accessioned_by',
            field=models.ForeignKey(help_text='Please select the user who accessioned the specimen', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accession',
            name='collection',
            field=models.ForeignKey(help_text='Please select the collection', on_delete=django.db.models.deletion.CASCADE, to='cms.collection'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='comment',
            field=models.TextField(blank=True, help_text='Any additional comments', null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='specimen_no',
            field=models.PositiveIntegerField(help_text='Please enter the specimen number'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='specimen_prefix',
            field=models.ForeignKey(help_text='Please select the specimen prefix', on_delete=django.db.models.deletion.CASCADE, to='cms.locality'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='type_status',
            field=models.CharField(blank=True, choices=[('Type', 'Type'), ('Holotype', 'Holotype'), ('Isotype', 'Isotype'), ('Lectotype', 'Lectotype'), ('Syntype', 'Syntype'), ('Isosyntype', 'Isosyntype'), ('Paratype', 'Paratype'), ('Neotype', 'Neotype'), ('Topotype', 'Topotype')], help_text='Please select the type status', max_length=50, null=True),
        ),
    ]
