# Generated by Django 4.1.13 on 2024-06-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_accession_accessioned_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldslip',
            name='accession',
        ),
    ]
