# Generated by Django 4.2.16 on 2024-11-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_reference_accessionreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
