# Generated by Django 4.2.16 on 2024-11-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_alter_reference_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='issue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
