# Generated by Django 4.2.16 on 2024-11-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_reference_issue_alter_reference_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='taxon_name',
            field=models.CharField(default='taxon', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxon',
            name='infraspecific_epithet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='scientific_name_authorship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='subfamily',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='superfamily',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='tribe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
