# Generated by Django 4.2.16 on 2024-11-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_alter_element_options_alter_element_parent_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessionrow',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.storage'),
        ),
    ]
