# Generated by Django 4.2.16 on 2024-11-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_alter_accessionrow_storage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessionrow',
            unique_together={('accession', 'specimen_suffix')},
        ),
    ]
