# Generated by Django 4.2.16 on 2024-12-04 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0019_alter_accessionrow_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeologicalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('geological_context_type', models.CharField(help_text='The type of geological context (e.g., Formation, Period, etc.)', max_length=255)),
                ('unit_name', models.CharField(help_text='The name of the geological unit (e.g., stratum, layer, etc.)', max_length=255)),
                ('name', models.CharField(help_text='The name of the geological context (e.g., name of the formation)', max_length=255)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('parent_geological_context', models.ForeignKey(blank=True, help_text='Parent geological context (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_geological_contexts', to='cms.geologicalcontext')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecimenGeology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('geological_context_type', models.CharField(help_text='The geological context type of the specimen', max_length=255)),
                ('accession', models.ForeignKey(help_text='Accession this specimen geology belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='specimen_geologies', to='cms.accession')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('earliest_geological_context', models.ForeignKey(blank=True, help_text='Earliest geological context of the specimen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earliest_geological_contexts', to='cms.geologicalcontext')),
                ('latest_geological_context', models.ForeignKey(blank=True, help_text='Latest geological context of the specimen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_geological_contexts', to='cms.geologicalcontext')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(help_text='The name of the media file', max_length=255)),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('text', 'Text'), ('other', 'Other')], help_text='Type of the media (e.g., photo, video, etc.)', max_length=50)),
                ('format', models.CharField(choices=[('jpg', 'JPG'), ('png', 'PNG'), ('mp4', 'MP4'), ('mp3', 'MP3'), ('pdf', 'PDF'), ('txt', 'TXT'), ('docx', 'DOCX'), ('other', 'Other')], help_text='File format of the media (e.g., jpg, png, mp4, etc.)', max_length=50)),
                ('media_location', models.CharField(help_text='The physical or digital location of the media file', max_length=255)),
                ('license', models.CharField(help_text='License information for the media file', max_length=255)),
                ('rights_holder', models.CharField(help_text='The individual or organization holding rights to the media', max_length=255)),
                ('accession', models.ForeignKey(help_text='Accession this media belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='cms.accession')),
                ('accession_row', models.ForeignKey(help_text='Accession row this media belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='cms.accessionrow')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
