# Generated by Django 4.2.18 on 2025-01-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_geologicalcontext_specimengeology_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='license',
            field=models.CharField(choices=[('jpg', 'JPG'), ('png', 'PNG'), ('mp4', 'MP4'), ('mp3', 'MP3'), ('pdf', 'PDF'), ('txt', 'TXT'), ('docx', 'DOCX'), ('other', 'Other')], default='CC0', help_text='License information for the media file', max_length=30),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_location',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
