# Generated by Django 4.2.18 on 2025-01-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_alter_media_accession_alter_media_accession_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.CharField(blank=True, choices=[('jpg', 'JPG'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('gif', 'GIF'), ('tiff', 'TIFF'), ('bmp', 'BMP')], help_text='File format of the media (e.g., jpg, png, mp4, etc.)', max_length=50, null=True),
        ),
    ]
