# Generated by Django 4.2.18 on 2025-02-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_alter_media_format'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessionreference',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='accessionreference',
            constraint=models.UniqueConstraint(fields=('accession', 'reference'), name='unique_accession_reference'),
        ),
    ]
