# Generated by Django 4.2.18 on 2025-02-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_alter_accessionreference_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessionrow',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='accessionrow',
            name='specimen_suffix',
            field=models.CharField(blank=True, default='-', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='accessionrow',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.storage'),
        ),
        migrations.AddIndex(
            model_name='accessionrow',
            index=models.Index(fields=['accession'], name='cms_accessi_accessi_d72722_idx'),
        ),
        migrations.AddIndex(
            model_name='accessionrow',
            index=models.Index(fields=['specimen_suffix'], name='cms_accessi_specime_545b55_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessionrow',
            constraint=models.UniqueConstraint(fields=('accession', 'specimen_suffix'), name='unique_accession_specimen_suffix'),
        ),
    ]
