# Generated by Django 4.2.18 on 2025-03-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_alter_accessionrow_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldslip',
            options={'ordering': ['field_number'], 'verbose_name': 'Field Slip'},
        ),
        migrations.AlterModelOptions(
            name='specimengeology',
            options={'ordering': ['accession'], 'verbose_name': 'Specimen Geology', 'verbose_name_plural': 'Specimen Geologies'},
        ),
        migrations.RemoveField(
            model_name='specimengeology',
            name='geological_context_type',
        ),
        migrations.AddField(
            model_name='accession',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='aerial_photo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='verbatim_element',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='verbatim_taxon',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identification',
            name='taxon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specimengeology',
            name='earliest_geological_context',
            field=models.ForeignKey(default=1, help_text='Earliest geological context of the specimen', on_delete=django.db.models.deletion.CASCADE, related_name='specimens_with_earliest_context', to='cms.geologicalcontext'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specimengeology',
            name='latest_geological_context',
            field=models.ForeignKey(default=1, help_text='Latest geological context of the specimen', on_delete=django.db.models.deletion.CASCADE, related_name='specimens_with_latest_context', to='cms.geologicalcontext'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='specimengeology',
            index=models.Index(fields=['accession'], name='cms_specime_accessi_75a39e_idx'),
        ),
        migrations.AddIndex(
            model_name='specimengeology',
            index=models.Index(fields=['earliest_geological_context'], name='cms_specime_earlies_8c7c40_idx'),
        ),
        migrations.AddIndex(
            model_name='specimengeology',
            index=models.Index(fields=['latest_geological_context'], name='cms_specime_latest__9d668d_idx'),
        ),
    ]
