# Generated by Django 4.2.20 on 2025-03-11 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0030_alter_fieldslip_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accession',
            options={'ordering': ['collection', 'specimen_prefix', 'specimen_no'], 'verbose_name': 'Accession', 'verbose_name_plural': 'Accessions'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-created_on'], 'verbose_name': 'Base Record', 'verbose_name_plural': 'Base Records'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name': 'Base Record', 'verbose_name_plural': 'Base Records'},
        ),
        migrations.AlterModelOptions(
            name='fieldslip',
            options={'ordering': ['field_number'], 'verbose_name': 'Field Slip', 'verbose_name_plural': 'Field Slips'},
        ),
        migrations.AlterModelOptions(
            name='geologicalcontext',
            options={'ordering': ['-created_on'], 'verbose_name': 'Base Record', 'verbose_name_plural': 'Base Records'},
        ),
        migrations.AlterModelOptions(
            name='identification',
            options={'ordering': ['-created_on'], 'verbose_name': 'Base Record', 'verbose_name_plural': 'Base Records'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created_on'], 'verbose_name': 'Base Record', 'verbose_name_plural': 'Base Records'},
        ),
        migrations.AlterModelOptions(
            name='natureofspecimen',
            options={'ordering': ['-created_on'], 'verbose_name': 'Base Record', 'verbose_name_plural': 'Base Records'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-created_on'], 'verbose_name': 'Base Record', 'verbose_name_plural': 'Base Records'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['-created_on'], 'verbose_name': 'Base Record', 'verbose_name_plural': 'Base Records'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['-created_on'], 'verbose_name': 'Base Record', 'verbose_name_plural': 'Base Records'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-created_on'], 'verbose_name': 'Base Record', 'verbose_name_plural': 'Base Records'},
        ),
        migrations.AlterField(
            model_name='accession',
            name='accessioned_by',
            field=models.ForeignKey(blank=True, help_text='User who accessioned the specimen.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accession',
            name='collection',
            field=models.ForeignKey(help_text='Select the collection this specimen belongs to.', on_delete=django.db.models.deletion.CASCADE, to='cms.collection'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional comments (if any).', null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='specimen_no',
            field=models.PositiveIntegerField(help_text='Enter the specimen number.'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='specimen_prefix',
            field=models.ForeignKey(help_text='Select the specimen prefix.', on_delete=django.db.models.deletion.CASCADE, to='cms.locality'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='type_status',
            field=models.CharField(blank=True, choices=[('Type', 'Type'), ('Holotype', 'Holotype'), ('Isotype', 'Isotype'), ('Lectotype', 'Lectotype'), ('Syntype', 'Syntype'), ('Isosyntype', 'Isosyntype'), ('Paratype', 'Paratype'), ('Neotype', 'Neotype'), ('Topotype', 'Topotype')], help_text='Select the type status.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accessionreference',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='accessionreference',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='accessionreference',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='accessionreference',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='accessionrow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='accessionrow',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='accessionrow',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='accessionrow',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='element',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='element',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='element',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='element',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='aerial_photo',
            field=models.CharField(blank=True, help_text='Aerial photo reference (if applicable).', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='collection_date',
            field=models.DateField(blank=True, help_text='Date the specimen was collected.', null=True),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='collector',
            field=models.CharField(blank=True, help_text='Person who collected the specimen.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='discoverer',
            field=models.CharField(blank=True, help_text='Person who discovered the specimen.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='field_number',
            field=models.CharField(help_text='Field number assigned to the specimen.', max_length=100),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='verbatim_SRS',
            field=models.CharField(blank=True, help_text='Spatial reference system used in the field.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='verbatim_coordinate_system',
            field=models.CharField(blank=True, help_text='Coordinate system used in the field (WGS84 etc.).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='verbatim_element',
            field=models.CharField(help_text='Skeletal element or fossil part recorded in the field.', max_length=255),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='verbatim_elevation',
            field=models.CharField(blank=True, help_text='Elevation as recorded.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='verbatim_horizon',
            field=models.CharField(blank=True, help_text='Geological horizon as recorded in the field.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='verbatim_latitude',
            field=models.CharField(blank=True, help_text='Latitude as recorded in the field.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='verbatim_locality',
            field=models.CharField(blank=True, help_text='Original locality description as recorded.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='verbatim_longitude',
            field=models.CharField(blank=True, help_text='Longitude as recorded in the field.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='verbatim_method',
            field=models.CharField(blank=True, help_text='Method used for discovery or collection (sieving etc.).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldslip',
            name='verbatim_taxon',
            field=models.CharField(help_text='Taxon name as recorded in the field.', max_length=255),
        ),
        migrations.AlterField(
            model_name='geologicalcontext',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='geologicalcontext',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='geologicalcontext',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='geologicalcontext',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='media',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='media',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='media',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='media',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='natureofspecimen',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='natureofspecimen',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='natureofspecimen',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='natureofspecimen',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='specimengeology',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='specimengeology',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='specimengeology',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='specimengeology',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.CreateModel(
            name='AccessionFieldSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('notes', models.TextField(blank=True, help_text='Additional notes.', null=True)),
                ('accession', models.ForeignKey(help_text='Select the accession.', on_delete=django.db.models.deletion.CASCADE, related_name='accession_fieldslips', to='cms.accession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('fieldslip', models.ForeignKey(help_text='Select the field slip.', on_delete=django.db.models.deletion.CASCADE, related_name='fieldslip_accessions', to='cms.fieldslip')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Accession-FieldSlip Link',
                'verbose_name_plural': 'Accession-FieldSlip Links',
                'ordering': ['accession', 'fieldslip'],
                'unique_together': {('accession', 'fieldslip')},
            },
        ),
    ]
