# Generated by Django 4.2.20 on 2025-03-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_alter_accession_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessionfieldslip',
            name='accession',
            field=models.ForeignKey(help_text='Select the accession.', on_delete=django.db.models.deletion.CASCADE, related_name='fieldslip_links', to='cms.accession'),
        ),
        migrations.AlterField(
            model_name='accessionfieldslip',
            name='fieldslip',
            field=models.ForeignKey(help_text='Select the field slip.', on_delete=django.db.models.deletion.CASCADE, related_name='accession_links', to='cms.fieldslip'),
        ),
    ]
