# Generated by Django 4.2.20 on 2025-04-01 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0032_alter_accessionfieldslip_accession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('preparation_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('consolidation', 'Consolidation'), ('casting', 'Casting'), ('repair', 'Repair'), ('restoration', 'Restoration'), ('conservation', 'Conservation'), ('mounting', 'Mounting'), ('other', 'Other')], help_text='The type of preparation or maintenance performed.', max_length=50)),
                ('reason', models.TextField(blank=True, help_text='The reason for the preparation (e.g., exhibition, conservation, research).', null=True)),
                ('started_on', models.DateField(help_text='Date when preparation started.')),
                ('completed_on', models.DateField(blank=True, help_text='Date when preparation was completed.', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', help_text='Current status of the preparation process.', max_length=20)),
                ('condition_before', models.TextField(blank=True, help_text='Condition of the specimen before preparation.', null=True)),
                ('condition_after', models.TextField(blank=True, help_text='Condition of the specimen after preparation.', null=True)),
                ('preparation_method', models.TextField(blank=True, help_text='Describe the preparation technique used (e.g., mechanical cleaning, acid preparation).', null=True)),
                ('chemicals_used', models.TextField(blank=True, help_text='List any chemicals or adhesives applied during the preparation.', null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', help_text='Approval decision by the curator.', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, help_text='Timestamp when the curator made a decision.', null=True)),
                ('curator_comments', models.TextField(blank=True, help_text="Curator's comments on the preparation (approval or rejection reasons).", null=True)),
                ('report_link', models.URLField(blank=True, help_text='Link to an external report or documentation for this preparation.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations about the preparation.', null=True)),
                ('accession_row', models.ForeignKey(help_text='The specimen undergoing preparation.', on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='cms.accessionrow')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('curator', models.ForeignKey(blank=True, help_text='The curator who reviews and approves/declines the preparation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_preparations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Base Record',
                'verbose_name_plural': 'Base Records',
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreparationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('name', models.CharField(help_text='Name of the preparation material (e.g., Paraloid B72, Cyanoacrylate).', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Details about the material (e.g., properties, best use cases).', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Base Record',
                'verbose_name_plural': 'Base Records',
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreparationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('changes', models.TextField(help_text='Description of changes made.')),
                ('changed_on', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the change.')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('preparation', models.ForeignKey(help_text='The preparation record that was modified.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cms.preparation')),
            ],
            options={
                'ordering': ['-changed_on'],
            },
        ),
        migrations.AddField(
            model_name='preparation',
            name='materials_used',
            field=models.ManyToManyField(blank=True, help_text='List of materials used in the preparation process.', related_name='preparations', to='cms.preparationmaterial'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='media',
            field=models.ManyToManyField(blank=True, help_text='Attach any media files related to the preparation (e.g., photos, videos).', related_name='preparations', to='cms.media'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='original_storage',
            field=models.ForeignKey(blank=True, help_text='Where the specimen was stored before preparation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_preparations', to='cms.storage'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='preparator',
            field=models.ForeignKey(blank=True, help_text='The museum staff responsible for the preparation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preparation',
            name='temporary_storage',
            field=models.ForeignKey(blank=True, help_text='Where the specimen was moved during preparation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_preparations', to='cms.storage'),
        ),
    ]
