# Generated by Django 4.2.20 on 2025-04-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_preparation_preparationmaterial_preparationlog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preparation',
            options={'verbose_name': 'Preparation', 'verbose_name_plural': 'Preparations'},
        ),
        migrations.AlterModelOptions(
            name='preparationlog',
            options={'ordering': ['-changed_on'], 'verbose_name': 'Preparation Log', 'verbose_name_plural': 'Preparation Logs'},
        ),
        migrations.AlterModelOptions(
            name='preparationmaterial',
            options={'verbose_name': 'Preparation Material', 'verbose_name_plural': 'Preparation Materials'},
        ),
    ]
