# Generated by Django 4.2.20 on 2025-04-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_alter_preparation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessionreference',
            options={'verbose_name': 'Accession Reference', 'verbose_name_plural': 'Accession References'},
        ),
        migrations.AlterModelOptions(
            name='accessionrow',
            options={'verbose_name': 'Accession Row', 'verbose_name_plural': 'Accession Rows'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Element', 'verbose_name_plural': 'Elements'},
        ),
        migrations.AlterModelOptions(
            name='geologicalcontext',
            options={'verbose_name': 'Geological Context', 'verbose_name_plural': 'Geological Contexties'},
        ),
        migrations.AlterModelOptions(
            name='identification',
            options={'verbose_name': 'Identification', 'verbose_name_plural': 'Identifications'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'Locality', 'verbose_name_plural': 'Localities'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Medias'},
        ),
        migrations.AlterModelOptions(
            name='natureofspecimen',
            options={'verbose_name': 'Nature Of Specimen', 'verbose_name_plural': 'Nature Of Specimens'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'Reference', 'verbose_name_plural': 'References'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Storage', 'verbose_name_plural': 'Storages'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.RemoveConstraint(
            model_name='accessionreference',
            name='unique_accession_reference',
        ),
    ]
