# Generated by Django 4.2.20 on 2025-04-01 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0035_alter_accessionreference_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('context', models.CharField(choices=[('before', 'Before Preparation'), ('after', 'After Preparation'), ('in_progress', 'In Progress'), ('other', 'Other')], default='other', help_text='Indicates when this media was captured.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional comments or observations about this media.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.media')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.preparation')),
            ],
            options={
                'verbose_name': 'Preparation Media',
                'verbose_name_plural': 'Preparation Media',
                'unique_together': {('preparation', 'media')},
            },
        ),
        migrations.AddField(
            model_name='preparation',
            name='media',
            field=models.ManyToManyField(blank=True, help_text='Attach categorized media (before/after/in-progress).', related_name='preparations', through='cms.PreparationMedia', to='cms.media'),
        ),
    ]
