# Generated by Django 4.2.20 on 2025-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_preparationmedia_alter_preparation_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='instance_number',
            field=models.PositiveIntegerField(default=1, help_text='Instance of the specimen number for handling known duplicates.'),
        ),
        migrations.AlterUniqueTogether(
            name='accession',
            unique_together={('specimen_no', 'specimen_prefix', 'instance_number')},
        ),
    ]
