# Generated by Django 4.2.20 on 2025-04-15 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0037_accession_instance_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionNumberSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_from', models.PositiveIntegerField()),
                ('end_at', models.PositiveIntegerField()),
                ('current_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accession_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'start_from'],
            },
        ),
    ]
