# Generated by Django 4.2.20 on 2025-04-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_accessionnumberseries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessionnumberseries',
            name='name',
        ),
    ]
