# Generated by Django 4.2.22 on 2025-08-08 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0043_unexpected_specimen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unexpectedspecimen',
            options={'verbose_name': 'Unexpected Specimen', 'verbose_name_plural': 'Unexpected Specimens'},
        ),
        migrations.AlterField(
            model_name='unexpectedspecimen',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='unexpectedspecimen',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
    ]
