# Generated by Django 4.2.22 on 2025-08-27 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cms", "0044_alter_unexpectedspecimen_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawerRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Date Modified"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Three letter unique code", max_length=3, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the drawer or folder"),
                ),
                (
                    "estimated_documents",
                    models.PositiveIntegerField(
                        help_text="Estimated number of documents or cards"
                    ),
                ),
                (
                    "scanning_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_progress", "In progress"),
                            ("scanned", "Scanned"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "localities",
                    models.ManyToManyField(
                        blank=True, help_text="Related localities", to="cms.locality"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "scanning_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users assigned to scanning",
                        related_name="drawerregisters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "taxa",
                    models.ManyToManyField(
                        blank=True, help_text="Related taxa", to="cms.taxon"
                    ),
                ),
            ],
            options={
                "verbose_name": "Drawer Register",
                "verbose_name_plural": "Drawer Register",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DrawerRegisterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Date Modified"),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[("status", "Status"), ("user", "User")], max_length=20
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_progress", "In progress"),
                            ("scanned", "Scanned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_progress", "In progress"),
                            ("scanned", "Scanned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "drawer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="cms.drawerregister",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drawer Register Log",
                "verbose_name_plural": "Drawer Register Logs",
                "ordering": ["-created_on"],
            },
        ),
    ]
