# Generated by Django 4.2.22 on 2025-09-02 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cms", "0045_drawerregister_drawerregisterlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(auto_now=True, verbose_name="Date Modified"),
                ),
                (
                    "relation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("partOf", "Part Of"),
                            ("synonym", "Synonym"),
                            ("abbreviation", "Abbreviation"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "place_type",
                    models.CharField(
                        choices=[
                            ("Region", "Region"),
                            ("Site", "Site"),
                            ("CollectingArea", "Collecting Area"),
                            ("square", "Square"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("part_of_hierarchy", models.CharField(editable=False, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="cms.locality",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "related_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_places",
                        to="cms.place",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
