# Generated by Django 4.2.22 on 2025-02-14

from django.conf import settings
from django.db import migrations


def migrate_logs_to_history(apps, schema_editor):
    DrawerRegisterLog = apps.get_model("cms", "DrawerRegisterLog")
    HistoricalDrawerRegister = apps.get_model("cms", "HistoricalDrawerRegister")

    for log in DrawerRegisterLog.objects.all():
        drawer = log.drawer

        HistoricalDrawerRegister.objects.create(
            id=drawer.id,
            created_on=drawer.created_on,
            modified_on=drawer.modified_on,
            code=drawer.code,
            description=drawer.description,
            estimated_documents=drawer.estimated_documents,
            scanning_status=log.new_status or drawer.scanning_status,
            created_by=drawer.created_by,
            modified_by=drawer.modified_by,
            history_date=log.created_on,
            history_user=log.created_by,
            history_type="~",
            history_change_reason=log.description or f"{log.change_type} change",
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cms", "0047_historicalunexpectedspecimen_historicaltaxon_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_logs_to_history, migrations.RunPython.noop),
        migrations.DeleteModel(name="HistoricalDrawerRegisterLog"),
        migrations.DeleteModel(name="DrawerRegisterLog"),
    ]

