# Generated by Django 4.2.22 on 2025-09-05 10:49

from django.db import migrations


def copy_preparation_logs(apps, schema_editor):
    PreparationLog = apps.get_model("cms", "PreparationLog")
    HistoricalPreparation = apps.get_model("cms", "HistoricalPreparation")
    fields = [
        field.name
        for field in HistoricalPreparation._meta.fields
        if field.name
        not in {"history_id", "history_date", "history_change_reason", "history_type", "history_user"}
    ]
    for log in PreparationLog.objects.all().order_by("changed_on"):
        prep = log.preparation
        data = {field: getattr(prep, field) for field in fields}
        data["history_date"] = log.changed_on
        data["history_user_id"] = log.changed_by_id
        data["history_type"] = "~"
        HistoricalPreparation.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0048_remove_drawerregisterlog"),
    ]

    operations = [
        migrations.RunPython(copy_preparation_logs, migrations.RunPython.noop),
        migrations.DeleteModel(name="HistoricalPreparationLog"),
        migrations.DeleteModel(name="PreparationLog"),
    ]
