# Generated by Django 4.2.22 on 2025-09-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0049_preparationlog_to_history"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drawerregister",
            options={
                "ordering": ["priority", "code"],
                "verbose_name": "Drawer Register",
                "verbose_name_plural": "Drawer Register",
            },
        ),
        migrations.AddField(
            model_name="drawerregister",
            name="priority",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order priority"
            ),
        ),
        migrations.AddField(
            model_name="historicaldrawerregister",
            name="priority",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order priority"
            ),
        ),
    ]
