# Generated by Django 4.2.22 on 2025-09-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0046_scanning"),
        ("cms", "0050_alter_drawerregister_options_drawerregister_priority_and_more"),
    ]

    operations = []
