# Generated by Django 4.2.22 on 2025-09-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0052_historicalscanning"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drawerregister",
            options={
                "ordering": ["-priority", "code"],
                "verbose_name": "Drawer Register",
                "verbose_name_plural": "Drawer Register",
            },
        ),
    ]
