# Generated by Django 4.2.22 on 2025-09-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0053_alter_drawerregister_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmedia",
            name="scanning",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Scanning session associated with this media",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="cms.scanning",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="scanning",
            field=models.ForeignKey(
                blank=True,
                help_text="Scanning session associated with this media",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media",
                to="cms.scanning",
            ),
        ),
    ]
