# Generated by Django 4.2.22 on 2025-09-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0054_historicalmedia_scanning_media_scanning"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmedia",
            name="ocr_data",
            field=models.JSONField(
                blank=True, help_text="OCR extracted data", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalmedia",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of OCR processing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="ocr_data",
            field=models.JSONField(
                blank=True, help_text="OCR extracted data", null=True
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of OCR processing",
                max_length=20,
            ),
        ),
    ]
