# Generated by Django 4.2.24 on 2025-09-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0055_historicalmedia_ocr_data_historicalmedia_ocr_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallocality",
            name="abbreviation",
            field=models.CharField(
                db_index=True,
                help_text="Enter the Abbreviation of the Locality",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="locality",
            name="abbreviation",
            field=models.CharField(
                help_text="Enter the Abbreviation of the Locality",
                max_length=2,
                unique=True,
            ),
        ),
    ]
