# Generated by Django 4.2.24 on 2025-09-23 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0058_historicalmedia_expert_checked_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmedia",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stable public identifier for the media entry.",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stable public identifier for the media entry.",
                unique=True,
            ),
        ),
    ]
