# Generated by Django 4.2.25 on 2025-10-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0060_llmusagerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusagerecord",
            name="processing_seconds",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Measured time spent processing the OCR request in seconds.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="llmusagerecord",
            name="remaining_quota_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latest remaining ChatGPT quota reported with this usage record.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
