# Generated by Django 4.2.25 on 2025-10-07 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cms", "0062_merge_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Date Created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Date Modified",
                    ),
                ),
                (
                    "model_label",
                    models.CharField(
                        help_text="Dotted label of the model the merge acted upon.",
                        max_length=255,
                    ),
                ),
                (
                    "source_pk",
                    models.CharField(
                        help_text="Primary key of the source record that was merged.",
                        max_length=255,
                    ),
                ),
                (
                    "target_pk",
                    models.CharField(
                        help_text="Primary key of the target record that received the data.",
                        max_length=255,
                    ),
                ),
                (
                    "resolved_values",
                    models.JSONField(
                        help_text="Final values applied to the target record."
                    ),
                ),
                (
                    "strategy_map",
                    models.JSONField(
                        help_text="Strategies that were used to resolve field conflicts."
                    ),
                ),
                (
                    "source_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="Serialised representation of the source record before merge.",
                        null=True,
                    ),
                ),
                (
                    "target_before",
                    models.JSONField(
                        help_text="Serialised state of the target record before the merge."
                    ),
                ),
                (
                    "target_after",
                    models.JSONField(
                        help_text="Serialised state of the target record after the merge."
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the merge completed.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who most recently updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that triggered the merge, when available.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Merge Log Entry",
                "verbose_name_plural": "Merge Log Entries",
                "ordering": ["-executed_at"],
            },
        ),
    ]
