# Generated by Django 4.2.25 on 2025-10-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0066_taxonomy_import_log"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="taxon",
            name="taxon_rank_idx",
        ),
        migrations.RemoveField(
            model_name="historicaltaxon",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicaltaxon",
            name="rank",
        ),
        migrations.RemoveField(
            model_name="taxon",
            name="name",
        ),
        migrations.RemoveField(
            model_name="taxon",
            name="rank",
        ),
        migrations.AddIndex(
            model_name="taxon",
            index=models.Index(fields=["taxon_rank"], name="taxon_rank_idx"),
        ),
    ]
