# Generated by Django 4.2.25 on 2025-11-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0067_remove_taxon_taxon_rank_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallocality",
            name="geological_times",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Selected geological time abbreviations for this locality.",
                verbose_name="Geological time",
            ),
        ),
        migrations.AddField(
            model_name="locality",
            name="geological_times",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Selected geological time abbreviations for this locality.",
                verbose_name="Geological time",
            ),
        ),
    ]
