# Generated by Django 4.2.26 on 2025-11-21 11:24

from django.db import migrations, models
import django.db.models.deletion


def populate_taxon_verbatim(apps, schema_editor):
    Identification = apps.get_model("cms", "Identification")

    identifications = Identification.objects.select_related("taxon_record").all()
    for identification in identifications.iterator(chunk_size=500):
        if identification.taxon_verbatim:
            continue

        if identification.taxon:
            verbatim = identification.taxon.strip()
        elif identification.taxon_record:
            verbatim = identification.taxon_record.taxon_name
        else:
            verbatim = None

        if verbatim:
            Identification.objects.filter(pk=identification.pk).update(
                taxon_verbatim=verbatim
            )


def noop_reverse(apps, schema_editor):
    """No-op reverse migration to keep forward data intact on rollback."""


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0068_historicallocality_geological_times_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalidentification",
            name="taxon_verbatim",
            field=models.CharField(
                blank=True,
                help_text="Verbatim taxon name provided during identification.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="identification",
            name="taxon_verbatim",
            field=models.CharField(
                blank=True,
                help_text="Verbatim taxon name provided during identification.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="identification",
            name="taxon_record",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked taxon from the controlled taxonomy.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="identifications",
                to="cms.taxon",
            ),
        ),
        migrations.RunPython(populate_taxon_verbatim, reverse_code=noop_reverse),
    ]
