# Generated by Django 4.2.26 on 2025-11-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0070_populate_taxon_verbatim_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalidentification",
            name="taxon_verbatim",
            field=models.CharField(
                blank=True,
                help_text="Lowest level of taxonomy provided for the identification; matched to the controlled taxonomy when possible.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="identification",
            name="taxon_verbatim",
            field=models.CharField(
                blank=True,
                help_text="Lowest level of taxonomy provided for the identification; matched to the controlled taxonomy when possible.",
                max_length=255,
                null=True,
            ),
        ),
    ]
