# Generated by Django 4.2.26 on 2025-11-26 10:19

from django.conf import settings
from django.db import migrations


def seed_organisations(apps, schema_editor):
    Organisation = apps.get_model("cms", "Organisation")
    UserOrganisation = apps.get_model("cms", "UserOrganisation")
    AccessionNumberSeries = apps.get_model("cms", "AccessionNumberSeries")
    HistoricalAccessionNumberSeries = apps.get_model(
        "cms", "HistoricalAccessionNumberSeries"
    )
    user_model = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    tbi_org, _ = Organisation.objects.get_or_create(
        code="tbi",
        defaults={"name": "Turkana Basin Institute"},
    )
    nmk_org, _ = Organisation.objects.get_or_create(
        code="nmk",
        defaults={"name": "National Museums of Kenya"},
    )

    tbi_user_ids = list(
        user_model.objects.filter(username__iexact="tbi").values_list("id", flat=True)
    )

    for user in user_model.objects.all():
        organisation = tbi_org if user.id in tbi_user_ids else nmk_org
        UserOrganisation.objects.update_or_create(
            user=user, defaults={"organisation": organisation}
        )

    for series in AccessionNumberSeries.objects.all():
        organisation = nmk_org
        if series.user_id in tbi_user_ids:
            organisation = tbi_org
        AccessionNumberSeries.objects.filter(pk=series.pk).update(
            organisation=organisation
        )

    if tbi_user_ids:
        HistoricalAccessionNumberSeries.objects.filter(
            user_id__in=tbi_user_ids
        ).update(organisation_id=tbi_org.id)
    HistoricalAccessionNumberSeries.objects.exclude(
        user_id__in=tbi_user_ids
    ).update(organisation_id=nmk_org.id)


def rollback_seed(apps, schema_editor):
    Organisation = apps.get_model("cms", "Organisation")
    UserOrganisation = apps.get_model("cms", "UserOrganisation")
    AccessionNumberSeries = apps.get_model("cms", "AccessionNumberSeries")
    HistoricalAccessionNumberSeries = apps.get_model(
        "cms", "HistoricalAccessionNumberSeries"
    )

    AccessionNumberSeries.objects.update(organisation=None)
    HistoricalAccessionNumberSeries.objects.update(organisation=None)
    UserOrganisation.objects.all().delete()
    Organisation.objects.filter(code__in=["tbi", "nmk"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0072_organisation_alter_accessionnumberseries_options_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_organisations, rollback_seed),
    ]
