# Generated by Django 4.2.27 on 2025-12-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0073_seed_organisations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="media_location",
            field=models.ImageField(
                help_text="Uploaded media file.", upload_to="uploads/"
            ),
        ),
    ]
