# Generated by Django 4.2.27 on 2025-12-10 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cms", "0074_alter_media_media_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="canonical_element",
            field=models.ForeignKey(
                blank=True,
                help_text="Canonical element that supersedes this record after merge.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_elements",
                to="cms.element",
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="merged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when this element was merged into the canonical record.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="merged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the merge.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_element_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalelement",
            name="canonical_element",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Canonical element that supersedes this record after merge.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="cms.element",
            ),
        ),
        migrations.AddField(
            model_name="historicalelement",
            name="merged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when this element was merged into the canonical record.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalelement",
            name="merged_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="User who performed the merge.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
