# Generated by Django 4.2.27 on 2025-12-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0074_alter_media_media_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="element",
            options={
                "ordering": ["parent_element__name", "name"],
                "permissions": [("can_merge", "Can merge element records")],
                "verbose_name": "Element",
                "verbose_name_plural": "Elements",
            },
        ),
    ]
