# Generated by Django 4.2.27 on 2025-12-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0075_alter_element_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accession",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="accessionfieldslip",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="preparationmedia",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.UniqueConstraint(
                fields=("specimen_no", "specimen_prefix", "instance_number"),
                name="unique_accession_specimen_instance",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessionfieldslip",
            constraint=models.UniqueConstraint(
                fields=("accession", "fieldslip"), name="unique_accession_fieldslip"
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationmedia",
            constraint=models.UniqueConstraint(
                fields=("preparation", "media"), name="unique_preparation_media"
            ),
        ),
    ]
