# Generated by Django 5.2.9 on 2026-01-30 11:35

import cms.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0077_ensure_accessionreference_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSpecimenListPDF",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Date Created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Date Modified",
                    ),
                ),
                (
                    "source_label",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized source label for the upload batch.",
                        max_length=255,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename provided at upload time.",
                        max_length=255,
                    ),
                ),
                (
                    "stored_file",
                    models.TextField(
                        help_text="Stored PDF file using UUID naming.", max_length=100
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 checksum for duplicate detection.",
                        max_length=64,
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of pages extracted from the PDF.",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the PDF was uploaded.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("split", "Split"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        help_text="Current processing status for the PDF.",
                        max_length=20,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who most recently updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who uploaded the PDF.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Specimen list PDF",
                "verbose_name_plural": "historical Specimen list PDFs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SpecimenListPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Date Created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Date Modified",
                    ),
                ),
                (
                    "source_label",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized source label for the upload batch.",
                        max_length=255,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename provided at upload time.",
                        max_length=255,
                    ),
                ),
                (
                    "stored_file",
                    models.FileField(
                        help_text="Stored PDF file using UUID naming.",
                        upload_to=cms.models.specimen_list_pdf_upload_to,
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 checksum for duplicate detection.",
                        max_length=64,
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of pages extracted from the PDF.",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the PDF was uploaded.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("split", "Split"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        help_text="Current processing status for the PDF.",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who most recently updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded the PDF.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specimen_list_pdfs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Specimen list PDF",
                "verbose_name_plural": "Specimen list PDFs",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalSpecimenListPage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Date Created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Date Modified",
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        help_text="Page number within the PDF (1-based)."
                    ),
                ),
                (
                    "image_file",
                    models.TextField(
                        blank=True,
                        help_text="Stored page image using UUID naming.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("specimen_list", "Specimen list"),
                            ("free_text", "Free text"),
                            ("typed_text", "Typed text"),
                            ("other", "Other"),
                        ],
                        default="unknown",
                        help_text="Classified page type.",
                        max_length=20,
                    ),
                ),
                (
                    "pipeline_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("classified", "Classified"),
                            ("ocr_done", "OCR done"),
                            ("extracted", "Extracted"),
                            ("in_review", "In review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Processing status within the ingestion pipeline.",
                        max_length=20,
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the page was locked for review.",
                        null=True,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the page was reviewed.",
                        null=True,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the page was approved.",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assigned_reviewer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Reviewer currently assigned to this page.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who most recently updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "pdf",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Parent specimen list PDF.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cms.specimenlistpdf",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Specimen list page",
                "verbose_name_plural": "historical Specimen list pages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SpecimenListPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Date Created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Date Modified",
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        help_text="Page number within the PDF (1-based)."
                    ),
                ),
                (
                    "image_file",
                    models.FileField(
                        blank=True,
                        help_text="Stored page image using UUID naming.",
                        null=True,
                        upload_to=cms.models.specimen_list_page_upload_to,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("specimen_list", "Specimen list"),
                            ("free_text", "Free text"),
                            ("typed_text", "Typed text"),
                            ("other", "Other"),
                        ],
                        default="unknown",
                        help_text="Classified page type.",
                        max_length=20,
                    ),
                ),
                (
                    "pipeline_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("classified", "Classified"),
                            ("ocr_done", "OCR done"),
                            ("extracted", "Extracted"),
                            ("in_review", "In review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Processing status within the ingestion pipeline.",
                        max_length=20,
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the page was locked for review.",
                        null=True,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the page was reviewed.",
                        null=True,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the page was approved.",
                        null=True,
                    ),
                ),
                (
                    "assigned_reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reviewer currently assigned to this page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specimen_list_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who most recently updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "pdf",
                    models.ForeignKey(
                        help_text="Parent specimen list PDF.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="cms.specimenlistpdf",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specimen list page",
                "verbose_name_plural": "Specimen list pages",
                "ordering": ["pdf", "page_number"],
                "indexes": [
                    models.Index(
                        fields=["pipeline_status"],
                        name="cms_specime_pipelin_674935_idx",
                    ),
                    models.Index(
                        fields=["page_type"], name="cms_specime_page_ty_b264eb_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pdf", "page_number"), name="uniq_specimen_page"
                    )
                ],
            },
        ),
    ]
