# Generated by Django 5.2.9 on 2025-01-08
from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0078_historicalspecimenlistpdf_specimenlistpdf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalspecimenlistpage",
            name="classification_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Classification confidence score between 0 and 1.",
                max_digits=4,
                null=True,
                validators=[
                    MinValueValidator(Decimal("0.0")),
                    MaxValueValidator(Decimal("1.0")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicalspecimenlistpage",
            name="classification_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes from the classification response.",
            ),
        ),
        migrations.AddField(
            model_name="historicalspecimenlistpage",
            name="classification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("classified", "Classified"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of page classification.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="specimenlistpage",
            name="classification_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Classification confidence score between 0 and 1.",
                max_digits=4,
                null=True,
                validators=[
                    MinValueValidator(Decimal("0.0")),
                    MaxValueValidator(Decimal("1.0")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="specimenlistpage",
            name="classification_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes from the classification response.",
            ),
        ),
        migrations.AddField(
            model_name="specimenlistpage",
            name="classification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("classified", "Classified"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of page classification.",
                max_length=20,
            ),
        ),
    ]
