# Generated by Django 5.2.9 on 2026-02-03 14:04

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0081_expand_specimen_list_page_type_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSpecimenListPageOCR",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        blank=True,
                        help_text="Raw OCR text extracted from the page image.",
                    ),
                ),
                (
                    "bounding_boxes",
                    models.JSONField(
                        blank=True,
                        help_text="OCR bounding box data captured from the OCR engine.",
                        null=True,
                    ),
                ),
                (
                    "ocr_engine",
                    models.CharField(
                        default="chatgpt-vision",
                        help_text="OCR engine identifier used to extract the text.",
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the OCR result was created.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Specimen list page associated with this OCR result.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cms.specimenlistpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Specimen list page OCR",
                "verbose_name_plural": "historical Specimen list page OCR entries",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSpecimenListRowCandidate",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "row_index",
                    models.PositiveIntegerField(
                        help_text="Row order within the page (0-based)."
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Extracted row data as JSON, including extra column keys."
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Confidence score for the extracted row between 0 and 1.",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("1.0")),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("edited", "Edited"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="unreviewed",
                        help_text="Review status for the row candidate.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the row candidate was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the row candidate was last updated.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Specimen list page associated with this row candidate.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cms.specimenlistpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Specimen list row candidate",
                "verbose_name_plural": "historical Specimen list row candidates",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SpecimenListPageOCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        blank=True,
                        help_text="Raw OCR text extracted from the page image.",
                    ),
                ),
                (
                    "bounding_boxes",
                    models.JSONField(
                        blank=True,
                        help_text="OCR bounding box data captured from the OCR engine.",
                        null=True,
                    ),
                ),
                (
                    "ocr_engine",
                    models.CharField(
                        default="chatgpt-vision",
                        help_text="OCR engine identifier used to extract the text.",
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the OCR result was created.",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Specimen list page associated with this OCR result.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_entries",
                        to="cms.specimenlistpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specimen list page OCR",
                "verbose_name_plural": "Specimen list page OCR entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ocr_engine"], name="cms_specime_ocr_eng_b937d0_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="cms_specime_created_cc8da9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SpecimenListRowCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_index",
                    models.PositiveIntegerField(
                        help_text="Row order within the page (0-based)."
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Extracted row data as JSON, including extra column keys."
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Confidence score for the extracted row between 0 and 1.",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("1.0")),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("edited", "Edited"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="unreviewed",
                        help_text="Review status for the row candidate.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the row candidate was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the row candidate was last updated.",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Specimen list page associated with this row candidate.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_candidates",
                        to="cms.specimenlistpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specimen list row candidate",
                "verbose_name_plural": "Specimen list row candidates",
                "ordering": ["page", "row_index"],
                "permissions": [
                    (
                        "review_specimenlistrowcandidate",
                        "Can review specimen list row candidates",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["status"], name="cms_specime_status_a47596_idx"
                    ),
                    models.Index(
                        fields=["page", "status"], name="cms_specime_page_id_666a65_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page", "row_index"), name="uniq_specimen_row_candidate"
                    )
                ],
            },
        ),
    ]
