# Generated by Django 5.2.9 on 2025-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0082_historicalspecimenlistpageocr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalspecimenlistpage",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
                help_text="Status of the human review workflow.",
            ),
        ),
        migrations.AddField(
            model_name="specimenlistpage",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
                help_text="Status of the human review workflow.",
            ),
        ),
        migrations.AddIndex(
            model_name="specimenlistpage",
            index=models.Index(fields=["review_status"], name="cms_specime_review__e1ae11_idx"),
        ),
    ]
