# Generated by Django 5.2.11 on 2026-02-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0085_historicalfieldslip_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnatureofspecimen",
            name="tooth_marking_detections",
            field=models.JSONField(
                blank=True,
                help_text="Tooth-marking detection metadata (token, notation, confidence, bbox, replacement_applied).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalnatureofspecimen",
            name="verbatim_element_raw",
            field=models.CharField(
                blank=True,
                help_text="Original extracted element text before tooth-marking correction.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="natureofspecimen",
            name="tooth_marking_detections",
            field=models.JSONField(
                blank=True,
                help_text="Tooth-marking detection metadata (token, notation, confidence, bbox, replacement_applied).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="natureofspecimen",
            name="verbatim_element_raw",
            field=models.CharField(
                blank=True,
                help_text="Original extracted element text before tooth-marking correction.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalnatureofspecimen",
            name="verbatim_element",
            field=models.CharField(
                blank=True,
                help_text="Element description used for QC and persistence.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="natureofspecimen",
            name="verbatim_element",
            field=models.CharField(
                blank=True,
                help_text="Element description used for QC and persistence.",
                max_length=255,
                null=True,
            ),
        ),
    ]
