# Generated by Django 5.2.11 on 2026-02-19 11:12

import django.db.models.deletion
from django.db import migrations, models


def seed_field_slip_vocabularies(apps, schema_editor):
    SedimentaryFeature = apps.get_model("cms", "SedimentaryFeature")
    GrainSize = apps.get_model("cms", "GrainSize")

    sedimentary_features = [
        {
            "name": "Root traces or burrows",
            "code": "ROOT_BUR",
            "category": "biogenic",
            "description": "Root casts or animal burrows within the sediment.",
        },
        {
            "name": "Cross-bedding",
            "code": "X_BEDS",
            "category": "sedimentary",
            "description": "Inclined internal bedding formed by current or wind transport.",
        },
        {
            "name": "Horizontal bedding",
            "code": "HORIZ_BEDS",
            "category": "sedimentary",
            "description": "Flat, parallel sedimentary layers.",
        },
        {
            "name": "Mud cracks",
            "code": "MUD_CRACKS",
            "category": "sedimentary",
            "description": "Desiccation cracks formed by drying mud.",
        },
        {
            "name": "Calcium carbonate nodules",
            "code": "CACO3_NOD",
            "category": "pedogenic",
            "description": "Carbonate concretions formed during soil development or groundwater precipitation.",
        },
        {
            "name": "Limonite nodules",
            "code": "LIMONITE_NOD",
            "category": "diagenetic",
            "description": "Iron oxide nodules formed during weathering or diagenesis.",
        },
        {
            "name": "Limonite fragments",
            "code": "LIMONITE_FRAGS",
            "category": "diagenetic",
            "description": "Broken pieces of iron-rich nodules or iron-cemented sediment.",
        },
    ]

    for feature in sedimentary_features:
        SedimentaryFeature.objects.update_or_create(code=feature["code"], defaults=feature)

    for name in ["Gravel", "Sand", "Silt", "Clay"]:
        GrainSize.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0086_historicalnatureofspecimen_tooth_marking_detections_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FossilGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GrainSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PreservationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SedimentaryFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sedimentary", "Sedimentary Structure"),
                            ("biogenic", "Biogenic Structure"),
                            ("pedogenic", "Pedogenic Feature"),
                            ("diagenetic", "Diagenetic Feature"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="fieldslip",
            name="collection_position",
            field=models.CharField(
                blank=True,
                choices=[("in_situ", "In situ"), ("ex_situ", "Ex situ (surface)")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fieldslip",
            name="matrix_association",
            field=models.CharField(
                blank=True,
                choices=[
                    ("attached", "Matrix attached"),
                    ("loose", "Loose matrix"),
                    ("none", "No matrix"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fieldslip",
            name="surface_exposure",
            field=models.BooleanField(
                blank=True,
                help_text="Specimen collected from exposed surface.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalfieldslip",
            name="collection_position",
            field=models.CharField(
                blank=True,
                choices=[("in_situ", "In situ"), ("ex_situ", "Ex situ (surface)")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalfieldslip",
            name="matrix_association",
            field=models.CharField(
                blank=True,
                choices=[
                    ("attached", "Matrix attached"),
                    ("loose", "Loose matrix"),
                    ("none", "No matrix"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalfieldslip",
            name="surface_exposure",
            field=models.BooleanField(
                blank=True,
                help_text="Specimen collected from exposed surface.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fieldslip",
            name="recommended_methods",
            field=models.ManyToManyField(
                blank=True,
                related_name="recommended_field_slips",
                to="cms.collectionmethod",
            ),
        ),
        migrations.AddField(
            model_name="fieldslip",
            name="fossil_groups",
            field=models.ManyToManyField(
                blank=True, related_name="field_slips", to="cms.fossilgroup"
            ),
        ),
        migrations.AddField(
            model_name="fieldslip",
            name="matrix_grain_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_slips",
                to="cms.grainsize",
            ),
        ),
        migrations.AddField(
            model_name="historicalfieldslip",
            name="matrix_grain_size",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="cms.grainsize",
            ),
        ),
        migrations.AddField(
            model_name="fieldslip",
            name="preservation_states",
            field=models.ManyToManyField(
                blank=True, related_name="field_slips", to="cms.preservationstate"
            ),
        ),
        migrations.AddField(
            model_name="fieldslip",
            name="sedimentary_features",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sedimentary, biogenic, pedogenic, or diagenetic features observed at the collection site.",
                related_name="field_slips",
                to="cms.sedimentaryfeature",
            ),
        ),
        migrations.RunPython(seed_field_slip_vocabularies, migrations.RunPython.noop),
    ]
