# Generated by Django 5.2.16 on 2026-09-15 14:12

from django.db import migrations, models


def consolidate_taxa(apps, schema_editor):
    """Keep one row per normalized name/rank and preserve catalogue references."""
    alias = schema_editor.connection.alias
    Taxon = apps.get_model("cms", "Taxon")
    Identification = apps.get_model("cms", "Identification")
    HistoricalIdentification = apps.get_model("cms", "HistoricalIdentification")
    HistoricalTaxon = apps.get_model("cms", "HistoricalTaxon")
    Drawer = apps.get_model("cms", "DrawerRegister")
    through = Drawer.taxa.through

    def label(value):
        return " ".join((value or "").split())

    groups = {}
    for taxon in Taxon.objects.using(alias).all().iterator():
        rank = label(taxon.taxon_rank).lower() or "species"
        key = rank + ":" + label(taxon.taxon_name).lower()
        groups.setdefault(key, []).append(taxon)
    redirects = {}
    survivors = {}
    for key, group in groups.items():
        def preference(taxon):
            non_mammal = label(taxon.class_name).lower() not in {"", "mammalia"}
            priority = (0 if taxon.external_source == "GBIF" and non_mammal else
                        1 if taxon.external_source == "NOW" else
                        2 if taxon.external_source == "GBIF" else 3)
            return priority, not taxon.is_active, taxon.status != "accepted", taxon.pk
        survivor = min(group, key=preference)
        survivors[survivor.pk] = (key, survivor)
        for taxon in group:
            if taxon.pk != survivor.pk:
                redirects[taxon.pk] = survivor.pk
    # Redirect all references before deleting any duplicate (including references
    # between duplicates). Historical rows retain their recorded taxonomy fields.
    for old_id, new_id in redirects.items():
        Identification.objects.using(alias).filter(taxon_record_id=old_id).update(taxon_record_id=new_id)
        HistoricalIdentification.objects.using(alias).filter(taxon_record_id=old_id).update(taxon_record_id=new_id)
        Taxon.objects.using(alias).filter(accepted_taxon_id=old_id).update(accepted_taxon_id=new_id)
        Taxon.objects.using(alias).filter(parent_id=old_id).update(parent_id=new_id)
        HistoricalTaxon.objects.using(alias).filter(accepted_taxon_id=old_id).update(accepted_taxon_id=new_id)
        HistoricalTaxon.objects.using(alias).filter(parent_id=old_id).update(parent_id=new_id)
        for drawer_id in through.objects.using(alias).filter(taxon_id=old_id).values_list("drawerregister_id", flat=True):
            through.objects.using(alias).get_or_create(drawerregister_id=drawer_id, taxon_id=new_id)
        through.objects.using(alias).filter(taxon_id=old_id).delete()
    for old_id in redirects:
        Taxon.objects.using(alias).filter(pk=old_id).delete()
    for survivor_id, (key, original) in survivors.items():
        taxon = Taxon.objects.using(alias).get(pk=survivor_id)
        changes = {"identity_key": key, "taxon_name": label(taxon.taxon_name), "taxon_rank": label(taxon.taxon_rank).lower() or "species"}
        if taxon.parent_id == taxon.pk:
            changes["parent_id"] = None
        if taxon.accepted_taxon_id == taxon.pk:
            changes.update(accepted_taxon_id=None, status="accepted")
        Taxon.objects.using(alias).filter(pk=survivor_id).update(**changes)

    taxa = {t.pk: t for t in Taxon.objects.using(alias).all()}
    by_name = {}
    for taxon in taxa.values():
        target = taxon if taxon.status == "accepted" else taxa.get(taxon.accepted_taxon_id)
        if taxon.is_active and target and target.is_active and target.status == "accepted":
            by_name.setdefault(label(taxon.taxon_name).lower(), set()).add(target.pk)
    for identification in Identification.objects.using(alias).all().iterator():
        recorded_name = label(identification.taxon_verbatim) or label(identification.taxon)
        targets = by_name.get(recorded_name.lower(), set())
        if len(targets) == 1:
            Identification.objects.using(alias).filter(pk=identification.pk).update(taxon_record_id=next(iter(targets)))


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0087_collectionmethod_fossilgroup_grainsize_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taxon',
            name='unique_taxon_rank_name_authorship',
        ),
        migrations.AddField(
            model_name='historicaltaxon',
            name='identity_key',
            field=models.CharField(db_index=True, default='', editable=False, max_length=320),
        ),
        migrations.AddField(
            model_name='taxon',
            name='identity_key',
            field=models.CharField(default='', editable=False, max_length=320),
        ),
        migrations.AlterField(
            model_name='historicaltaxon',
            name='external_source',
            field=models.CharField(choices=[('GBIF', 'GBIF / Catalogue of Life'), ('NOW', 'NOW'), ('PBDB', 'PBDB'), ('LEGACY', 'Legacy')], default='LEGACY', help_text='External source that provided this taxon.', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicaltaxon',
            name='taxon_name',
            field=models.CharField(help_text='Primary taxon name for the selected rank.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaltaxonomyimport',
            name='source',
            field=models.CharField(choices=[('NOW_GBIF', 'NOW + GBIF'), ('NOW', 'NOW')], default='NOW', help_text='External taxonomy source for this import.', max_length=16),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='external_source',
            field=models.CharField(choices=[('GBIF', 'GBIF / Catalogue of Life'), ('NOW', 'NOW'), ('PBDB', 'PBDB'), ('LEGACY', 'Legacy')], default='LEGACY', help_text='External source that provided this taxon.', max_length=16),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='taxon_name',
            field=models.CharField(help_text='Primary taxon name for the selected rank.', max_length=255),
        ),
        migrations.AlterField(
            model_name='taxonomyimport',
            name='source',
            field=models.CharField(choices=[('NOW_GBIF', 'NOW + GBIF'), ('NOW', 'NOW')], default='NOW', help_text='External taxonomy source for this import.', max_length=16),
        ),
        migrations.RunPython(consolidate_taxa, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='taxon', name='identity_key',
            field=models.CharField(default='', editable=False, max_length=320, unique=True),
        ),
    ]
