# Generated by Django 5.2.16 on 2026-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0088_remove_taxon_unique_taxon_rank_name_authorship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaxon',
            name='author_year',
            field=models.TextField(blank=True, help_text='Authorship information associated with the name.'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='author_year',
            field=models.TextField(blank=True, help_text='Authorship information associated with the name.'),
        ),
    ]
