# Generated by Django 5.2.16 on 2026-09-21 13:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0090_backfill_historical_taxon_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAICreditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('balance', 'Verified balance'), ('adjustment', 'Top-up / adjustment')], max_length=16)),
                ('amount_usd', models.DecimalField(decimal_places=6, help_text='Balance, or signed adjustment: positive for top-ups, negative for expired credits.', max_digits=18)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the balance was checked or the adjustment took effect.')),
                ('note', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OpenAI credit entry',
                'verbose_name_plural': 'OpenAI credit entries',
                'ordering': ['-effective_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'effective_at'), name='openai_credit_org_time_unique')],
            },
        ),
        migrations.CreateModel(
            name='OpenAIBillingSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(max_length=255, unique=True)),
                ('coverage_start', models.DateField(null=True)),
                ('costs_through', models.DateTimeField(null=True)),
                ('last_success_at', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('spend_since_balance_usd', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('balance_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.openaicreditentry')),
            ],
        ),
        migrations.CreateModel(
            name='OpenAIDailyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(max_length=255)),
                ('project_id', models.CharField(blank=True, max_length=255)),
                ('day', models.DateField()),
                ('amount_usd', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'project_id', 'day'), name='openai_cost_org_project_day')],
            },
        ),
    ]
